//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string ID { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public string MANV { get; set; }
        public string MALOAI { get; set; }
    
        public virtual LOAINHANVIEN LOAINHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
