//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOTRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOTRI()
        {
            this.CTBAOTRIs = new HashSet<CTBAOTRI>();
        }
    
        public string MABAOTRI { get; set; }
        public Nullable<int> TONGTHOIGIANBAOTRI { get; set; }
        public string MANV { get; set; }
        public string MAXE { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBAOTRI> CTBAOTRIs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual XE XE { get; set; }
    }
}
