//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBAOTRI
    {
        public string MACTBAOTRI { get; set; }
        public string MABAOTRI { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> THOIGIANBAOTRI { get; set; }
        public string MATHIETBI { get; set; }
    
        public virtual BAOTRI BAOTRI { get; set; }
        public virtual TRANGTHIETBI TRANGTHIETBI { get; set; }
    }
}
