//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDDOBAOHO
    {
        public string MAHD { get; set; }
        public string MADBH { get; set; }
        public string MALOAIDBH { get; set; }
        public Nullable<double> DONGIA { get; set; }
    
        public virtual DOBAOHO DOBAOHO { get; set; }
        public virtual HOADONBANVE HOADONBANVE { get; set; }
        public virtual LOAIDOBAOHO LOAIDOBAOHO { get; set; }
    }
}
