//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAPXE
    {
        public string MAPN { get; set; }
        public string MANCC { get; set; }
        public string TENXE { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
    
        public virtual NHACC NHACC { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
