//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOBAOHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOBAOHO()
        {
            this.CTHDDOBAOHOes = new HashSet<CTHDDOBAOHO>();
        }
    
        public string MADOBAOHO { get; set; }
        public string TENDOBAOHO { get; set; }
        public string MALOAIDBH { get; set; }
        public string MANHACC { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDDOBAOHO> CTHDDOBAOHOes { get; set; }
        public virtual LOAIDOBAOHO LOAIDOBAOHO { get; set; }
    }
}
