//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONTHUEHLV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONTHUEHLV()
        {
            this.HOADONTHUEHLVCTXEs = new HashSet<HOADONTHUEHLVCTXE>();
        }
    
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string MANV { get; set; }
        public string MAKH { get; set; }
        public string MAHLV { get; set; }
        public string MADV { get; set; }
    
        public virtual DICHVUTHUEHLV DICHVUTHUEHLV { get; set; }
        public virtual HUANLUYENVIEN HUANLUYENVIEN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONTHUEHLVCTXE> HOADONTHUEHLVCTXEs { get; set; }
    }
}
