//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONTHUEHLVCTXE
    {
        public string MAHD { get; set; }
        public string MAXE { get; set; }
        public Nullable<bool> DEOBIET { get; set; }
    
        public virtual HOADONTHUEHLV HOADONTHUEHLV { get; set; }
        public virtual XE XE { get; set; }
    }
}
