//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOATDONG
    {
        public string MAXE { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.TimeSpan> BATDAU { get; set; }
        public Nullable<System.TimeSpan> THOIGIAN { get; set; }
        public string MAHLV { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string MAHD { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual XE XE { get; set; }
    }
}
