//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_KVCEntities : DbContext
    {
        public QL_KVCEntities()
            : base("name=QL_KVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<BAOTRI> BAOTRIs { get; set; }
        public virtual DbSet<CTBAOTRI> CTBAOTRIs { get; set; }
        public virtual DbSet<CTHDDOBAOHO> CTHDDOBAOHOes { get; set; }
        public virtual DbSet<CTHOADONBANVE> CTHOADONBANVEs { get; set; }
        public virtual DbSet<CTPHIEUNHAPDBH> CTPHIEUNHAPDBHs { get; set; }
        public virtual DbSet<CTPHIEUNHAPTTB> CTPHIEUNHAPTTBs { get; set; }
        public virtual DbSet<CTPHIEUNHAPXE> CTPHIEUNHAPXEs { get; set; }
        public virtual DbSet<DICHVUTHUEHLV> DICHVUTHUEHLVs { get; set; }
        public virtual DbSet<DOBAOHO> DOBAOHOes { get; set; }
        public virtual DbSet<HOADONBANVE> HOADONBANVEs { get; set; }
        public virtual DbSet<HOADONTHUEHLV> HOADONTHUEHLVs { get; set; }
        public virtual DbSet<HOADONTHUEHLVCTXE> HOADONTHUEHLVCTXEs { get; set; }
        public virtual DbSet<HOATDONG> HOATDONGs { get; set; }
        public virtual DbSet<HUANLUYENVIEN> HUANLUYENVIENs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIDOBAOHO> LOAIDOBAOHOes { get; set; }
        public virtual DbSet<LOAINHANVIEN> LOAINHANVIENs { get; set; }
        public virtual DbSet<LOAIVE> LOAIVEs { get; set; }
        public virtual DbSet<NHACC> NHACCs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<TRANGTHIETBI> TRANGTHIETBIs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    }
}
