//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAP()
        {
            this.CTPHIEUNHAPDBHs = new HashSet<CTPHIEUNHAPDBH>();
            this.CTPHIEUNHAPTTBs = new HashSet<CTPHIEUNHAPTTB>();
            this.CTPHIEUNHAPXEs = new HashSet<CTPHIEUNHAPXE>();
        }
    
        public string MAPN { get; set; }
        public Nullable<int> LOAIPN { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string MANV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAPDBH> CTPHIEUNHAPDBHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAPTTB> CTPHIEUNHAPTTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAPXE> CTPHIEUNHAPXEs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
