//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHIETBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANGTHIETBI()
        {
            this.CTBAOTRIs = new HashSet<CTBAOTRI>();
            this.CTPHIEUNHAPTTBs = new HashSet<CTPHIEUNHAPTTB>();
        }
    
        public string MATHIETBI { get; set; }
        public string TENTHIETBI { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string MANCC { get; set; }
        public Nullable<int> TONKHO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBAOTRI> CTBAOTRIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAPTTB> CTPHIEUNHAPTTBs { get; set; }
        public virtual NHACC NHACC { get; set; }
    }
}
