//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVC_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.BAOTRIs = new HashSet<BAOTRI>();
            this.CTHOADONBANVEs = new HashSet<CTHOADONBANVE>();
            this.HOADONTHUEHLVCTXEs = new HashSet<HOADONTHUEHLVCTXE>();
        }
    
        public string MAXE { get; set; }
        public string TENXE { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string MANCC { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOTRI> BAOTRIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADONBANVE> CTHOADONBANVEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONTHUEHLVCTXE> HOADONTHUEHLVCTXEs { get; set; }
        public virtual HOATDONG HOATDONG { get; set; }
        public virtual NHACC NHACC { get; set; }
    }
}
